FROM cgr.dev/chainguard/python:latest-dev as builder

WORKDIR /app

# Copy pip.conf for custom package index
COPY pip.conf /etc/pip.conf

COPY frontend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt --user

FROM cgr.dev/chainguard/python:latest

WORKDIR /app

COPY --from=builder /home/nonroot/.local /home/nonroot/.local
COPY frontend/ .

ENV PATH=/home/nonroot/.local/bin:$PATH

CMD ["python", "src/server.py"]
