FROM cgr.dev/chainguard/python:latest-dev AS builder

WORKDIR /app

# Copy pip.conf for custom package index
COPY pip.conf /etc/pip.conf

COPY backend/requirements.txt requirements.txt

RUN python -m venv /app/venv && \
    /app/venv/bin/pip install --no-cache-dir -r requirements.txt

FROM cgr.dev/chainguard/python:latest

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PATH="/venv/bin:$PATH"

COPY backend/ .
COPY --from=builder /app/venv /venv

ENTRYPOINT [ "python", "wsgi.py" ]
